### ISSUE TITLE
用openblock-link-desktop时，总是报这个错

### ISSUE THREAD

**Issue by dongkuang** [AITosee/Sentry-Arduino#7]
开始报错
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `bodyMatch':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:94: undefined reference to `tosee_sentry::HwSentryUart::read(unsigned char*, unsigned int)'
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:96: undefined reference to `tosee_sentry::HwSentryUart::read(unsigned char*, unsigned int)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `headMatch':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:79: undefined reference to `tosee_sentry::HwSentryUart::read(unsigned char*, unsigned int)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `receive':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:56: undefined reference to `tosee_sentry::PtotocolAnalysis::pushPackage(unsigned char, tosee_sentry::pkg_t const&)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `transmit':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:72: undefined reference to `tosee_sentry::HwSentryUart::write(unsigned char*, unsigned int)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `__base_dtor ':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:24: undefined reference to `tosee_sentry::HwSentryUart::~HwSentryUart()'
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:24: undefined reference to `tosee_sentry::PtotocolAnalysis::~PtotocolAnalysis()'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `__base_ctor ':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry/sentry_i2c.cpp:6: undefined reference to `tosee_sentry::HwSentryI2C::HwSentryI2C(TwoWire*, unsigned long)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `__base_ctor ':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:23: undefined reference to `tosee_sentry::PtotocolAnalysis::PtotocolAnalysis(unsigned int, unsigned char)'
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry\protoc/sentry_protocol_analysis.h:23: undefined reference to `tosee_sentry::HwSentryUart::HwSentryUart(Stream*)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o: In function `__base_dtor ':
C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry/sentry_i2c.cpp:10: undefined reference to `tosee_sentry::HwSentryI2C::~HwSentryI2C()'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x30): undefined reference to `tosee_sentry::HwSentryI2C::I2CRead(unsigned char, unsigned char*)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x32): undefined reference to `tosee_sentry::HwSentryI2C::I2CWrite(unsigned char, unsigned char)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x5c): undefined reference to `tosee_sentry::HwSentryUart::available()'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x5e): undefined reference to `tosee_sentry::HwSentryUart::read(unsigned char*, unsigned int)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x60): undefined reference to `tosee_sentry::HwSentryUart::write(unsigned char*, unsigned int)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x76): undefined reference to `tosee_sentry::HwSentryUart::available()'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x78): undefined reference to `tosee_sentry::HwSentryUart::read(unsigned char*, unsigned int)'
C:\Users\TG\AppData\Local\Temp\ccJGmXrK.ltrans0.ltrans.o:(.rodata+0x7a): undefined reference to `tosee_sentry::HwSentryUart::write(unsigned char*, unsigned int)'
collect2.exe: error: ld returned 1 exit status
Using library Wire at version 1.0 in folder: C:\Program Files\openblock-link-desktop\resources\tools\Arduino\packages\arduino\hardware\avr\1.8.3\libraries\Wire
Using library Sentry in folder: C:\Program Files\openblock-link-desktop\resources\tools\Arduino\libraries\Sentry (legacy)

Error during build: exit status 1

Build failed
上传错误

**Comment by AITosee** [comment]
似乎是库路径问题，我们官方没有支持过这个图形化软件，你是 `openblock-link-desktop` 开发者吗 @dongkuang
