### ISSUE TITLE
Sentry1的色块识别

### ISSUE THREAD

**Issue by Lost151551** [AITosee/Sentry-Arduino#9]
能不能提供一个能识别其他图形色块的代码

**Comment by Lost151551** [comment]
类似三角形，圆形这样的识别

**Comment by AITosee** [comment]
抱歉，当前Sentry1暂不直接支持形状识别。

Sentry2可以通过 `深度学习` 算法来记忆不同颜色不同形状的色块，可参考文档：https://tosee.readthedocs.io/zh/latest/Sentry2/Vision/index.html#chapter-vision-learning-index
及例程：https://github.com/AITosee/Sentry-Arduino/blob/main/examples/Sentry2/Learning/Learning.ino
